version: "3.1"

services:

  ya_kusov_bot:
    container_name: ya_bot
    build:
      context: .
    command: python bot.py
    restart: always
    networks:
      - botnet
    volumes:
      - .:/ya_kusov_bot
    environment:
      - TZ=Europe/Moscow
    env_file:
      - ".env"


networks:
  botnet:
    driver: bridge
